### ISSUE TITLE
Model weights

### ISSUE THREAD

**Issue by rbareja25** [birkhoffkiki/GPFM#2]
Hello,

I am unable to locate the model weights for this? Could you assist?

Rohan

**Comment by birkhoffkiki** [comment]
you could download weights from `Releases`

**Comment by rbareja25** [comment]
Also is it a vit-large based model?Is it compatible with https://github.com/facebookresearch/dino/blob/7c446df5b9f45747937fb0d72314eb9f7b66930a/vision_transformer.py#L236

**Comment by birkhoffkiki** [comment]
the configuration is located at https://github.com/birkhoffkiki/GPFM/blob/2f93ebccd5ca0fe85397bf328372909de65eaa7a/models/dinov2/__init__.py#L32. I also update the readme file, see https://github.com/birkhoffkiki/GPFM/tree/master?tab=readme-ov-file#only-using-feature-extractor
