### ISSUE TITLE
GPFM Patch Size

### ISSUE THREAD

**Issue by scjjb** [birkhoffkiki/GPFM#3]
To clarify, for GPFM is it expected that the input patches will be 512x512 before the following transforms turn the patches into 224x224 pixels?

 normalize = transforms.Compose([
        transforms.Resize((size, size), interpolation=3), 
        transforms.ToTensor(),
        transforms.Normalize(mean=mean, std=std)])

(taken from https://github.com/birkhoffkiki/GPFM/blob/15d93000c67046976c10f98c0c4877ca2305dd05/models/dinov2/__init__.py#L65)

**Comment by birkhoffkiki** [comment]
Yes. (512*512 patch is  40x)
